version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    labels:
      - dependencies
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'
    reviewers:
      - jrolfs
    commit-message:
      prefix: feat
      prefix-development: build
      include: scope
    versioning-strategy: increase
