version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    pull-request-branch-name:
      separator: '-'
    commit-message:
      prefix: 'feat(deps):'
      prefix-development: 'build(deps):'
      include: 'scope'
