version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    labels:
      - dependencies
      - automerge
    schedule:
      interval: daily
    pull-request-branch-name:
      separator: '-'
    commit-message:
      prefix: feat
      prefix-development: build
      include: scope
    versioning-strategy: increase
