language: node_js

node_js:
  - '8'
  - '10'
  - '12'

sudo: false
notifications:
  email: false
cache:
  directories:
    - node_modules

script: yarn validate

jobs:
  include:
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: 'node src travis-after-success'
