version: '1.0'

indicators:
  - x-common_pull_request_conditions: &common_pull_request_conditions
      when:
        branch:
          ignore:
            - master
            - next

  - x-common_release_conditions: &common_release_conditions
      when:
        branch:
          only:
            - master
            - next

stages:
  - prepare
  - build
  - release

steps:
  main_clone:
    stage: prepare
    type: 'git-clone'
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_BRANCH}}'
  build:
    stage: build
    image: node:12.18.2-alpine
    commands:
      - yarn install
  test:
    stage: build
    image: node:12.18.2-alpine
    commands:
      - yarn validate
  coverage:
    <<: *common_pull_request_conditions
    stage: build
    image: node:12.18.2-alpine
    commands:
      - yarn ci-after-success
  releaser:
    <<: *common_release_conditions
    stage: release
    type: build
    image_name: '${{CF_REPO_NAME}}-releaser'
    dockerfile: Dockerfile
  release:
    <<: *common_release_conditions
    stage: release
    image: ${{releaser}}
    commands:
      - yarn build
      - yarn ci-after-success
