version: '1.0'

stages:
  - prepare
  - build
  - release

steps:
  main_clone:
    stage: prepare
    type: 'git-clone'
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_BRANCH}}'
  build:
    stage: build
    image: node:10.16.0-alpine
    commands:
      - yarn install
  test:
    stage: build
    image: node:10.16.0-alpine
    commands:
      - yarn validate
  releaser:
    stage: release
    type: build
    image_name: releaser
    dockerfile: Dockerfile
  release:
    stage: release
    image: ${{releaser}}
    commands:
      - yarn build
      - echo "${SSH_KEY}" | tr  ',' '\n' > "/etc/ssh/id_rsa"
      - node src travis-after-success
