version: '1.0'

stages:
  - clone
  - build
  - release

steps:
  clone:
    stage: clone
    type: 'git-clone'
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_BRANCH}}'
  build:
    stage: build
    image: node:10.16.0-alpine
    working_directory: ${{clone}}
    commands:
      - yarn install
  test:
    stage: build
    image: ${{build}}
    commands:
      - yarn validate
  release:
    stage: release
    image: ${{build}}
    commands:
      - yarn build
      - node src travis-after-success
