version: '1.0'

indicators:
  - common_release_conditions: &common_release_conditions
      when:
        branch:
          only:
            - master

stages:
  - prepare
  - build
  - release

steps:
  main_clone:
    stage: prepare
    type: 'git-clone'
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_BRANCH}}'
  build:
    stage: build
    image: node:10.19.0-alpine
    commands:
      - yarn install
  test:
    stage: build
    image: node:10.19.0-alpine
    commands:
      - yarn validate
  releaser:
    <<: *common_release_conditions
    stage: release
    type: build
    image_name: '${{CF_REPO_NAME}}-releaser'
    dockerfile: Dockerfile
  release:
    <<: *common_release_conditions
    stage: release
    image: ${{releaser}}
    commands:
      - yarn build
      - node src ci-after-success
