name: Merge
on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: 'pascalgn/automerge-action@v0.14.1'
        env:
          GITHUB_TOKEN: '${{ secrets.AUTOMERGE_TOKEN }}'
          MERGE_LABELS: 'automerge,!work in progress'
          MERGE_REMOVE_LABELS: 'automerge'
          MERGE_METHOD: 'rebase'
          MERGE_COMMIT_MESSAGE: 'pull-request-description'
          MERGE_FORKS: 'false'
          MERGE_RETRIES: '6'
          MERGE_RETRY_SLEEP: '10000'
          UPDATE_LABELS: 'autoupdate'
          UPDATE_METHOD: 'rebase'
